<script setup>
import { computed, onMounted, reactive, ref } from "vue";
import { useRoute } from "vue-router";
import AdminLayout from "../../layouts/AdminLayout.vue";
import StatusBadge from "../../components/StatusBadge.vue";
import { userService } from "../../services/api";

const users = ref([]), error = ref(""), toast = ref(""), filter = ref(""), editing = ref(null);
const route = useRoute();
const form = reactive({ nom_complet: "", departement: "", poste: "", role: "utilisateur", statut: "en_attente" });
const filteredUsers = computed(() => users.value.filter((user) => !filter.value || user.statut === filter.value));
const load = async () => { try { users.value = (await userService.list()).data; const selected = users.value.find((user) => user.id === Number(route.query.user)); if (selected) open(selected); } catch (exception) { error.value = exception.message; } };
const open = (user) => { editing.value = user; Object.assign(form, { nom_complet: user.nom_complet, departement: user.departement, poste: user.poste, role: user.role, statut: user.statut }); document.getElementById("user-modal").showModal(); };
const save = async () => { try { await userService.update(editing.value.id, form); document.getElementById("user-modal").close(); toast.value = "Utilisateur mis à jour."; await load(); } catch (exception) { error.value = exception.message; } };
const act = async (user, action) => { if (action === "reject" && !confirm(`Refuser le compte de ${user.nom_complet} ?`)) return; try { await userService[action](user.id); toast.value = `Compte ${action === "approve" ? "approuvé" : "refusé"}.`; await load(); } catch (exception) { error.value = exception.message; } };
onMounted(load);
</script>
<template><AdminLayout><section class="p-5 md:p-10"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 class="text-3xl font-bold">Utilisateurs</h1><p class="mt-2 text-slate-500">Consultez, validez et mettez à jour les comptes.</p></div><select v-model="filter" class="select select-bordered select-sm"><option value="">Tous les statuts</option><option value="en_attente">En attente</option><option value="approuve">Approuvés</option><option value="refuse">Refusés</option></select></div><div v-if="error" class="alert alert-error mt-6">{{ error }}</div><div v-else class="mt-7 overflow-x-auto rounded-2xl bg-white shadow-sm"><table class="table"><thead><tr><th>Nom</th><th>Email</th><th>Département</th><th>Poste</th><th>Rôle</th><th>Statut</th><th>Inscription</th><th></th></tr></thead><tbody><tr v-for="user in filteredUsers" :key="user.id"><td><button class="font-semibold text-[#17482d] hover:underline" @click="open(user)">{{ user.nom_complet }}</button></td><td>{{ user.email }}</td><td>{{ user.departement }}</td><td>{{ user.poste }}</td><td class="capitalize">{{ user.role }}</td><td><StatusBadge :status="user.statut" /></td><td>{{ user.date_creation ? new Date(user.date_creation).toLocaleDateString('fr-FR') : '—' }}</td><td class="flex gap-2"><button class="btn btn-outline btn-xs" @click="open(user)">Modifier</button><button v-if="user.statut === 'en_attente'" class="btn btn-success btn-xs" @click="act(user, 'approve')">Approuver</button><button v-if="user.statut === 'en_attente'" class="btn btn-error btn-xs" @click="act(user, 'reject')">Refuser</button></td></tr><tr v-if="!filteredUsers.length"><td colspan="8" class="py-10 text-center text-slate-500">Aucun utilisateur trouvé.</td></tr></tbody></table></div><dialog id="user-modal" class="modal"><div class="modal-box"><form method="dialog"><button class="btn btn-circle btn-ghost btn-sm absolute right-3 top-3">✕</button></form><h2 class="text-xl font-bold">Fiche utilisateur</h2><p class="mt-1 text-sm text-slate-500">{{ editing?.email }}</p><form class="mt-5 grid gap-3" @submit.prevent="save"><input v-model="form.nom_complet" class="input input-bordered" placeholder="Nom complet" required><input v-model="form.departement" class="input input-bordered" placeholder="Département" required><input v-model="form.poste" class="input input-bordered" placeholder="Poste" required><select v-model="form.role" class="select select-bordered"><option value="utilisateur">Utilisateur</option><option value="administrateur">Administrateur</option></select><select v-model="form.statut" class="select select-bordered"><option value="en_attente">En attente</option><option value="approuve">Approuvé</option><option value="refuse">Refusé</option></select><button class="btn border-0 bg-[#17482d] text-white">Enregistrer les modifications</button></form></div></dialog><div v-if="toast" class="toast toast-end"><div class="alert alert-success">{{ toast }}</div></div></section></AdminLayout></template>
