<script setup>
import { useRouter } from "vue-router";
import { useAuthStore } from "../stores/auth";
import NotificationBell from "./NotificationBell.vue";
const auth = useAuthStore(); const router = useRouter();
const logout = () => { auth.logout(); router.push("/login"); };
</script>
<template>
  <div class="bg-[#17482d] px-5 py-2 text-xs text-white"><div class="mx-auto flex max-w-7xl items-center justify-between"><span>Gestion du parc informatique</span><span class="hidden sm:block">Plateforme de gestion du matériel informatique</span><button class="underline" @click="logout">Déconnexion</button></div></div>
  <header class="border-b border-white/70 bg-white/75 backdrop-blur-xl"><nav class="navbar mx-auto min-h-18 max-w-7xl px-4 sm:px-5"><RouterLink to="/catalogue" class="text-xl font-bold tracking-tight text-[#17482d]">InfoTech</RouterLink><div class="ml-auto hidden items-center gap-1 md:flex"><RouterLink class="btn btn-ghost btn-sm" to="/catalogue">Catalogue</RouterLink><RouterLink class="btn btn-ghost btn-sm" to="/demandes">Mes demandes</RouterLink><RouterLink v-if="auth.isAdmin" class="btn btn-ghost btn-sm" to="/admin">Administration</RouterLink><NotificationBell /><RouterLink to="/profil" class="ml-2 flex items-center gap-2 text-sm font-medium text-slate-600"><span class="grid h-8 w-8 place-items-center overflow-hidden rounded-full bg-[#dcecdf] font-bold text-[#17482d]"><img v-if="auth.user?.avatar_url" :src="auth.user.avatar_url" class="h-full w-full object-cover"><span v-else>{{ auth.user?.nom_complet?.[0] }}</span></span><span>{{ auth.user?.nom_complet }}</span></RouterLink></div><div class="ml-auto flex items-center gap-2 md:hidden"><NotificationBell /><details class="dropdown dropdown-end"><summary class="btn btn-ghost btn-square" aria-label="Ouvrir le menu">☰</summary><ul class="menu dropdown-content z-50 mt-3 w-56 rounded-box bg-white p-2 shadow-xl"><li><RouterLink to="/catalogue">Catalogue</RouterLink></li><li><RouterLink to="/demandes">Mes demandes</RouterLink></li><li><RouterLink to="/profil">Mon profil</RouterLink></li><li v-if="auth.isAdmin"><RouterLink to="/admin">Administration</RouterLink></li><li><button @click="logout">Déconnexion</button></li></ul></details></div></nav></header>
</template>
