"""creation des tables initiales

Revision ID: 1e28afcc55e3
Revises: 
Create Date: 2026-09-27 12:32:04.855045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e28afcc55e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mot_de_passe_hache', sa.String(length=255), nullable=False),
    sa.Column('nom_complet', sa.String(length=100), nullable=False),
    sa.Column('departement', sa.String(length=100), nullable=False),
    sa.Column('poste', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('approuve_par_admin_id', sa.Integer(), nullable=True),
    sa.Column('date_traitement', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approuve_par_admin_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateurs_id'), 'utilisateurs', ['id'], unique=False)
    op.create_table('journaux_audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('administrateur_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('type_cible', sa.String(length=50), nullable=False),
    sa.Column('cible_id', sa.Integer(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['administrateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journaux_audit_id'), 'journaux_audit', ['id'], unique=False)
    op.create_table('materiels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('categorie', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantite_totale', sa.Integer(), nullable=False),
    sa.Column('quantite_disponible', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('cree_par_admin_id', sa.Integer(), nullable=False),
    sa.Column('modifie_par_admin_id', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.CheckConstraint('quantite_disponible >= 0', name='ck_materiels_quantite_disponible'),
    sa.CheckConstraint('quantite_totale >= 0', name='ck_materiels_quantite_totale'),
    sa.ForeignKeyConstraint(['cree_par_admin_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['modifie_par_admin_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materiels_id'), 'materiels', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=150), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('est_lu', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('demandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('materiel_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('motif', sa.Text(), nullable=False),
    sa.Column('type_emprunt', sa.String(length=20), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin_prevue', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('motif_refus', sa.Text(), nullable=True),
    sa.Column('traite_par_admin_id', sa.Integer(), nullable=True),
    sa.Column('date_traitement', sa.DateTime(), nullable=True),
    sa.Column('retour_traite_par_admin_id', sa.Integer(), nullable=True),
    sa.Column('date_retour_effective', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['materiel_id'], ['materiels.id'], ),
    sa.ForeignKeyConstraint(['retour_traite_par_admin_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['traite_par_admin_id'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demandes_id'), 'demandes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_demandes_id'), table_name='demandes')
    op.drop_table('demandes')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_materiels_id'), table_name='materiels')
    op.drop_table('materiels')
    op.drop_index(op.f('ix_journaux_audit_id'), table_name='journaux_audit')
    op.drop_table('journaux_audit')
    op.drop_index(op.f('ix_utilisateurs_id'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    # ### end Alembic commands ###
