<script setup>
import { reactive, ref } from "vue";
import UserLayout from "../../layouts/UserLayout.vue";
import { authService } from "../../services/api";
import { useAuthStore } from "../../stores/auth";
const auth = useAuthStore(); const form = reactive({ nom_complet: auth.user?.nom_complet || "", departement: auth.user?.departement || "", poste: auth.user?.poste || "", avatar_url: auth.user?.avatar_url || null, mot_de_passe_actuel: "", nouveau_mot_de_passe: "" }); const message = ref(""), error = ref("");
const image = (event) => { const file = event.target.files?.[0]; if (!file || !file.type.startsWith("image/")) return; const reader = new FileReader(); reader.onload = () => { form.avatar_url = reader.result; }; reader.readAsDataURL(file); };
const save = async () => { message.value = ""; error.value = ""; try { await authService.updateProfile(form); await auth.restore(); message.value = "Profil enregistré avec succès."; form.mot_de_passe_actuel = ""; form.nouveau_mot_de_passe = ""; } catch (exception) { error.value = exception.message; } };
</script>
<template><UserLayout><section class="mx-auto max-w-4xl px-5 py-10"><div class="glass-panel overflow-hidden"><div class="bg-gradient-to-r from-[#164a2d] to-[#397758] px-6 py-8 text-white"><p class="text-sm font-medium text-green-100">Espace personnel</p><h1 class="m-0 mt-1 text-3xl text-white">Mon profil</h1></div><form class="grid gap-7 p-6 md:grid-cols-[180px_1fr] md:p-8" @submit.prevent="save"><aside class="text-center"><div class="mx-auto grid h-28 w-28 place-items-center overflow-hidden rounded-full bg-[#dcecdf] text-4xl font-bold text-[#17482d]"><img v-if="form.avatar_url" :src="form.avatar_url" class="h-full w-full object-cover"><span v-else>{{ form.nom_complet?.[0] }}</span></div><label class="btn btn-outline btn-sm mt-4 cursor-pointer">Changer la photo<input class="hidden" type="file" accept="image/*" @change="image"></label></aside><div class="grid gap-4"><label class="form-control"><span class="label-text">Nom complet</span><input v-model="form.nom_complet" class="input input-bordered" required></label><div class="grid gap-4 sm:grid-cols-2"><label class="form-control"><span class="label-text">Département</span><input v-model="form.departement" class="input input-bordered" required></label><label class="form-control"><span class="label-text">Poste</span><input v-model="form.poste" class="input input-bordered" required></label></div><div class="mt-2 border-t border-slate-100 pt-5"><h2 class="text-lg font-bold">Modifier le mot de passe</h2><div class="mt-3 grid gap-3 sm:grid-cols-2"><input v-model="form.mot_de_passe_actuel" type="password" class="input input-bordered" placeholder="Mot de passe actuel"><input v-model="form.nouveau_mot_de_passe" type="password" minlength="8" class="input input-bordered" placeholder="Nouveau mot de passe"></div></div><p v-if="error" class="text-sm text-error">{{ error }}</p><p v-if="message" class="text-sm text-success">{{ message }}</p><button class="btn border-0 bg-gradient-to-r from-[#17482d] to-[#397758] text-white">Enregistrer les modifications</button></div></form></div></section></UserLayout></template>
